### ISSUE TITLE
Address code TODOs

### ISSUE THREAD

**Issue by ravewebdev** [WebDevStudios/nextjs-wordpress-starter#383]
Address various TODOs across project.

### Misc
- [x] AcfBlockMediaText: TODO: Query the DB for the image ID and replace the attributes.data with the correct information - existing issue #378 @ravewebdev 
- [x] BlockParagraph: TODO Add settings for unused props in default WP Paragraph Block @itsamoreh (FE) @ravewebdev (BE)
- [ ] isLinkActive: TODO: Add functionality to check if link is in the full URL path @johnrobertmcc 
- [ ] App: TODO -- abstract this to a component. @johnrobertmcc 
- [x] BlogPost: @ravewebdev 
    - [x] TODO: use response to display next "page" of posts
    - [x] TODO create generic archive component and move this check to `_app.js`
- [ ] Profile: TODO - Possibly create a model for User @johnrobertmcc 
- [x] Team: @ravewebdev 
    - [x] TODO: use response to display next "page" of posts
    - [x] TODO create generic archive component and move this check to `_app.js`

### Storybook
- [ ] Search: TODO: Create Storybook for this component @itsamoreh
- [ ] Footer: TODO: Create Storybook for this component @itsamoreh #411 
- [ ] Header: TODO: Create Storybook for this component @itsamoreh #411 
- [ ] AlgoliaResults: TODO: Create Storybook for this component @itsamoreh 

### Blocked/on-hold
- [x] processGfFieldValues: TODO: As of WP GraphQL Gravity Forms v.0.4.1, this is accurate, but it appears it may be changing to a nested version in the next release: fieldValue.emailValues = { value, confirmationValue }
- [x] Fields: TODO: re-add support for FileUploadField once file uploads are supported via WP GraphQL Gravity Forms - existing issue #380

**Comment by ravewebdev** [comment]
4/26 EOD
* Hooked up archive pagination: #385
* Abstracted archive functionality to component: #393
